# Site settings
title: Martin Krasser's Blog
home: Blog
header-img: img/distributed.png
description: ""
baseurl: ""
url: "http://krasserm.github.io"
twitter_username: mrt1nz
github_username:  krasserm
linkedin_username: krasserm

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems:
  - jekyll-sitemap